[project]
name = "mine-database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.18"
dependencies = [
    "pymongo>=4.10.1",
    "rdkit>=2024.3.6",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
